## Basic Configuration

baseurl = "https://valentinaroman.ro"
builddrafts = false
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Valentina Roman"
title = "Valentina Roman"

theme = "dream"

defaultContentLanguage = "en"


## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-24119774-2"
enableRobotsTXT = true

[params]
  background = "#fff"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  backgroundDark = "black"
  darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  images = [""]

  headerTitle = "Valentina Roman"
  motto = "I am a digital project manager with a 360° perspective, passionate about understanding what makes projects truly successful and why. I’ve worn every hat in the communication domain: from PR to marketing, from content writing to e-commerce growth strategies, from managing volunteers to business development, from CSR campaigns to product development and AI technologies.<br><br>In my spare time, I am writing about my experience in managing diverse teams while directly reporting to high-profile senior managers. Take your moment to read my articles as I hope you will find them useful and inspiring!"

  avatar = "/img/valentina_roman.jpg"

  # maxTags = 5
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  rss = true

  email = "valentina.st.roman@gmail.com"
  twitter = "valentinaroman"
  facebook = "valentinaroman"
  instagram = "valentinaroman"
  linkedin = "valentinaroman"

  siteStartYear = 2021

  favicon = "/favicon.ico"

  # search
  enableSearch = false
