name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Yarn install
      - uses: borales/actions-yarn@v2.3.0
        working-directory: ./themes/dream
        with:
          cmd: install # will run `yarn install` command

      - name: Yarn build
      - uses: borales/actions-yarn@v2.3.0
        working-directory: ./themes/dream
        with:
          cmd: prod # will run `yarn prod` command

      - name: Build hugo
        run: hugo --minify

      - name: Deploy github pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
